
#macro NETWORK_BUFFER_SIZE_S8 1 
#macro NETWORK_BUFFER_SIZE_S16 2
#macro NETWORK_BUFFER_SIZE_S32 4

#macro NETWORK_BUFFER_SIZE_F16 2
#macro NETWORK_BUFFER_SIZE_F32 4
#macro NETWORK_BUFFER_SIZE_F64 8

#macro NETWORK_BUFFER_SIZE_U8 1
#macro NETWORK_BUFFER_SIZE_U16 2
#macro NETWORK_BUFFER_SIZE_U32 4
#macro NETWORK_BUFFER_SIZE_U64 8

#macro NETWORK_BUFFER_SIZE_BOOL 1
#macro NETWORK_BUFFER_SIZE_TEXT 0
#macro NETWORK_BUFFER_SIZE_STRING 0

#macro NETWORK_DATA_TYPE_VAR_TYPE buffer_u8

enum NET_DATA {
	UNKNOW = 0,
	CONNECT,
	DISCONECT,
	SERVER_CLOSE,
	GAME_START,
	
	TTT_BUTTON_INPUT,
	TTT_GAME_SNAPSHOT,
}

#macro NETDATA_VAR_TYPE_U8			"NETDATA_VAR_U8"
#macro NETDATA_VAR_TYPE_U16			"NETDATA_VAR_U16"
#macro NETDATA_VAR_TYPE_U32			"NETDATA_VAR_U32"
#macro NETDATA_VAR_TYPE_U64			"NETDATA_VAR_U64"
																
#macro NETDATA_VAR_TYPE_S8			"NETDATA_VAR_S8"
#macro NETDATA_VAR_TYPE_S16			"NETDATA_VAR_S16"
#macro NETDATA_VAR_TYPE_S32			"NETDATA_VAR_S32"
																
#macro NETDATA_VAR_TYPE_F16			"NETDATA_VAR_F16"
#macro NETDATA_VAR_TYPE_F32			"NETDATA_VAR_F32"
#macro NETDATA_VAR_TYPE_F64			"NETDATA_VAR_F64"

#macro NETDATA_VAR_TYPE_TEXT		"NETDATA_VAR_TEXT"
#macro NETDATA_VAR_TYPE_BOOL		"NETDATA_VAR_BOOL"
#macro NETDATA_VAR_TYPE_STRING	"NETDATA_VAR_STRING"

#macro NETDATA_VAR_TYPE_GRID		"NETDATA_VAR_GRID"

