
#macro NETWORK_BUFFER_SIZE_S8 1 
#macro NETWORK_BUFFER_SIZE_S16 2
#macro NETWORK_BUFFER_SIZE_S32 4

#macro NETWORK_BUFFER_SIZE_F16 2
#macro NETWORK_BUFFER_SIZE_F32 4
#macro NETWORK_BUFFER_SIZE_F64 8

#macro NETWORK_BUFFER_SIZE_U8 1
#macro NETWORK_BUFFER_SIZE_U16 2
#macro NETWORK_BUFFER_SIZE_U32 4
#macro NETWORK_BUFFER_SIZE_U64 8

#macro NETWORK_BUFFER_SIZE_BOOL 1
#macro NETWORK_BUFFER_SIZE_TEXT 0
#macro NETWORK_BUFFER_SIZE_STRING 0

#macro NETWORK_DATA_TYPE_VAR_TYPE buffer_u8

enum NET_DATA {
	UNKNOW = 0,
	CONNECT,
	DISCONECT,
	SERVER_CLOSE,
	GAME_START,
}
